sudo: required
dist: bionic

language: generic

compiler:
  - gcc

env:
  global:
    - CATKIN_WS=~/catkin_ws
    - CATKIN_WS_SRC=${CATKIN_WS}/src
    - CI_ROS_DISTRO="melodic"

install:
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/ros-latest.list'
  - echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" | sudo tee /etc/apt/sources.list.d/gazebo-stable.list
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python-rosdep python-catkin-tools
  - sudo rosdep init
  - rosdep update
  # Use rosdep to install all dependencies (including ROS itself)
  # - git clone https://github.com/RoboticaUtnFrba/i2c_imu.git $TRAVIS_BUILD_DIR/i2c_imu
  - git clone https://github.com/RoboticaUtnFrba/libcreate.git $TRAVIS_BUILD_DIR/libcreate
  - rosdep install --from-paths ./ -i -y --rosdistro $CI_ROS_DISTRO
  # Install and compile RTIMULib2
  - git clone https://github.com/RoboticaUtnFrba/RTIMULib2.git $TRAVIS_BUILD_DIR/RTIMULib2
  - cd $TRAVIS_BUILD_DIR/RTIMULib2/Linux && mkdir build && cd build
  - sudo apt-get install -qq -y libqt4-dev libqt4-opengl-dev
  - cmake ..
  - make -j4
  - sudo make install
  - sudo ldconfig
  # Finish installation
  - source /opt/ros/$CI_ROS_DISTRO/setup.bash
  - mkdir -p $CATKIN_WS_SRC
  # Add the package under integration to the workspace using a symlink
  - ln -s $TRAVIS_BUILD_DIR $CATKIN_WS_SRC

script:
  - source /opt/ros/$CI_ROS_DISTRO/setup.bash
  - cd $CATKIN_WS
  # Build packages
  - catkin_make -DCMAKE_BUILD_TYPE=Release
  # Run the tests, ensuring the path is set correctly.
  - source devel/setup.bash
  # Run tests
  - catkin_make run_tests && catkin_test_results
  # Lint package files
  - sudo apt-get install python-catkin-lint
  - catkin lint -W2 --strict --explain src/create_autonomy --ignore plugin_missing_install --ignore missing_depend --ignore target_name_collision
  # Tips
  #
  # C++:
  # ----
  # sudo apt-get install astyle
  # find -regextype egrep -regex '.*\.[ch](pp)?$' -exec astyle '{}' --style=allman --indent=spaces=2 --pad-oper --unpad-paren --pad-header --convert-tabs \;
  #
  # Python:
  # -------
  # sudo pip install pep8ify
  # pep8ify -nw .
  - catkin_make roslint